### ISSUE TITLE
Forex.analytics npm install error Node 16.4.1

### ISSUE THREAD

**Issue by Tristaan** [carlos8f/zenbot#2749]
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Archlinux
- **Zenbot version** (commit ref, or version): 4.1.4
- **Zenbot branch**: unstable
- **NodeJS version**: 16.4.1
- **Python version (when using a python script)**:
- **Exact command to reproduce (include everything)**: npm install --production || npm install
- **Did I make any changes to conf-sample.js?**: no

### Describe the problem
The installation errors out when trying to run the node-gyp builds hooks. Exact error below. It tries to search for some V8::Handle which does not exist. The cause for this is most likely the forex.analytics module.
This happened when I upgraded from xy unstable to 4.1.4.

### Source code / Error logs
```
npm ERR! gyp info using node-gyp@8.1.0
npm ERR! gyp info using node@16.4.1 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/../include/BinaryTreeFitness.h:3,
npm ERR!                  from ../src/BinaryTreeFitness.cpp:1:
npm ERR! ../src/../include/BinaryTreeChromosome.h:133:23: error: ‘v8::Handle’ has not been declared
npm ERR!   133 |         void ToJs(v8::Handle<v8::Object>& input) const;
npm ERR!       |                       ^~~~~~
npm ERR! ../src/../include/BinaryTreeChromosome.h:133:29: error: expected ‘,’ or ‘...’ before ‘<’ token
npm ERR!   133 |         void ToJs(v8::Handle<v8::Object>& input) const;
npm ERR!       |                             ^
npm ERR! make: *** [analytics.target.mk:135: Release/obj.target/analytics/src/BinaryTreeFitness.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
```
